version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
    - "5433:5432"
    environment:
        POSTGRES_PASSWORD: example
  
  redis:
    image: redis 
    restart: always
    ports:
      - "6379:6379"